template_path: production/cloudwatch.yaml
parameters:
  SNSTopicName: !stack_output production/sns.yaml::SNSTopicName
  DashboardName: {{ dashboard_name }}
  BucketName: !stack_output production/s3.yaml::BucketName
